### ISSUE TITLE
text going off screen on the right side

### ISSUE THREAD

**Issue by TrellBell** [Chokage/Fear-And-Hunger-Android-Application#6]
In many of the text boxes the words will be cut off on the right side of the screen. It's not game breaking but it makes quickly reading the text more of a chore. Not sure if others are having this issue.

**Comment by Lalysaaaelys** [comment]
same things for me, I've tried with the modded version and the original one, on 1.0.4

**Comment by Chokage** [comment]
Sorry : ( 

That's an issue with the game's engine itself, since the textlines aren't optimized for phones. 
However, try adjusting the resolution in settings to something more compact to see if it helps.
Sorry I'm unable to fix this bug.
